//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Code_CH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoGiaoHang
    {
        public int maBaoCaoGiaoHang { get; set; }
        public Nullable<int> maSP { get; set; }
        public Nullable<int> soluongSP { get; set; }
        public Nullable<System.DateTime> ngaygiao { get; set; }
        public Nullable<System.DateTime> ngaythanhCong { get; set; }
        public Nullable<int> maDH { get; set; }
    }
}
